library(cmdstanr)
library(jsonlite)
mod <- cmdstan_model('m1_base_topology.stan')
data <- read_json('data/stan_data_N30.json', simplifyVector = TRUE)
data$min_RT <- min(data$RT)
cat('Model compiled.\n')
fit <- mod$pathfinder(data = data, num_paths = 4, single_path_draws = 1000)
fit$save_object('m1_fit.rds')
cat('Model fitting complete.\n')
