library(cmdstanr)
library(jsonlite)
library(loo)
mod <- cmdstan_model('d1_base_distillation.stan')
data <- read_json('data/stan_data_N30_distilled.json', simplifyVector = TRUE)
data$min_RT <- min(data$RT)
fit <- mod$pathfinder(data = data, num_paths = 4, single_path_draws = 1000)
fit$save_object('d1_fit.rds')
log_lik <- fit$draws('log_lik')
loo_res <- loo(log_lik)
cat(sprintf('Model Codename: D1_Base_Distillation\nELPD: %.2f (SE: %.2f)\n', loo_res$estimates['elpd_loo', 'Estimate'], loo_res$estimates['elpd_loo', 'SE']))
