library(cmdstanr)
library(jsonlite)
mod <- cmdstan_model('m3_sparse_expansion.stan')
data <- read_json('data/stan_data_N30.json', simplifyVector = TRUE)
data$min_RT <- min(data$RT)
cat('M3 Model compiled.\n')
fit <- mod$pathfinder(data = data, num_paths = 4, single_path_draws = 1000)
fit$save_object('m3_fit.rds')
cat('M3 Model fitting complete.\n')
