library(cmdstanr)
library(jsonlite)
mod <- cmdstan_model('d4_hybrid_distillation.stan')
data <- read_json('data/stan_data_N100_mddm.json', simplifyVector = TRUE)
data$min_RT <- min(data$RT)
fit <- mod$pathfinder(data = data, num_paths = 4, single_path_draws = 1000)
fit$save_object('d4_hybrid_fit.rds')
cat('D4 Hybrid Distillation Pathfinder completed successfully.\n')
cat(sprintf('Generative Empirical ELPD: %.2f\n', mean(fit$draws(variables = "sum_log_lik"))))
