library(cmdstanr)
library(jsonlite)
mod <- cmdstan_model('d2_moment_matching_distillation.stan')
data <- read_json('data/stan_data_N30_distilled.json', simplifyVector = TRUE)
data$min_RT <- min(data$RT)
fit <- mod$pathfinder(data = data, num_paths = 4, single_path_draws = 1000)
fit$save_object('d2_fit.rds')
cat('D2 Moment Matching Distillation Pathfinder completed successfully.\n')
cat(sprintf('Target ELPD (via Pathfinder approximation): %.2f\n', mean(fit$lp())))
