library(cmdstanr)
library(jsonlite)
mod <- cmdstan_model('m2_softplus_compression.stan')
data <- read_json('data/stan_data_N30.json', simplifyVector = TRUE)
data$min_RT <- min(data$RT)
cat('M2 Model compiled.\n')
fit <- mod$pathfinder(data = data, num_paths = 4, single_path_draws = 1000)
fit$save_object('m2_fit.rds')
cat('M2 Model fitting complete.\n')
